name: Add Scroll to some tool or library
description: This brings Scroll compatibility into an existing library or project
title: Add Scroll to
labels: ["integration"]
body:
  - type: input
    id: integration_name
    attributes:
      label: "Name of the project"
      placeholder: "Zerolend"
    validations:
      required: true
  - type: dropdown
    id: integration_type
    attributes:
      label: "Tool"
      options: 
        - Library
        - Tool
    validations:
      required: true
  - type: input
    id: integration_site_link
    attributes:
      label: "Site of the project"
      placeholder: "https://zerolend.xyz/"
    validations:
      required: false
  - type: input
    id: integration_github_link
    attributes:
      label: "Github repository of the project"
      placeholder: "https://github.com/zerolend"
    validations:
      required: true
  - type: dropdown
    id: integration_network
    attributes:
      label: "Networks"
      description: "Scroll Mainnet"
      multiple: true
      options:
        - Scroll Testnet - Sepolia
        - Scroll Mainnet
    validations:
      required: true
  - type: textarea
    id: integration_description
    attributes:
      label: "Additional context"
      description: "Zerolend is Dapp to provide Borrowing and lending on Metis and ZKsyinc network, i think its important to implement Zerolend to Scroll "
    validations:
      required: false
